"""LaTeX table bodies for the working documents of the study, generated from results files.
  results/table_theorem2.tex : d, L_d, best computed lower bound (Rayleigh-Ritz), U_d, ratio, sqrt(U_d), sqrt(2 d U_d),
                               article constant 2 sqrt(1 + 1/(d pi^2))
  results/table_eta_by_d.tex : (problem, method, d): seed-mean relative error, B_int, B_bd, eta (min-max), share (min-max)
  results/table_budget.tex   : d = 10 networks at 4000 iterations, 16 000 iterations and equal CPU."""
import json, math, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))
from t2common import U, L, RES, load_jsonl

best = {1: (0.5, "exact")}
for r in json.load(open(os.path.join(RES, "theorem2_checks.json")))["A6_lanczos"]:
    if r["lam_max"] > best.get(r["d"], (0, ""))[0]:
        best[r["d"]] = (r["lam_max"], f"full, K={r['K']}")
for r in json.load(open(os.path.join(RES, "restricted_lanczos.json")))["rows"]:
    if r["lam"] > best.get(r["d"], (0, ""))[0]:
        best[r["d"]] = (r["lam"], f"r={r['r']}, K={r['K']}")
with open(os.path.join(RES, "table_theorem2.tex"), "w") as f:
    f.write("% generated by scripts/s8_tables.py from results/theorem2_checks.json and results/restricted_lanczos.json\n")
    for d in [1, 2, 3, 4, 5, 10, 20, 50, 100]:
        lo, how = best.get(d, (float("nan"), "-"))
        f.write(f"{d} & {L(d):.4f} & {lo:.4f} & {U(d):.4f} & {lo/U(d):.3f} & {math.sqrt(U(d)):.3f} & {math.sqrt(2*d*U(d)):.3f} & "
                f"{2*math.sqrt(1+1/(d*math.pi**2)):.3f} \\\\  % lower bound from {how}\n")
json.dump({str(k): v for k, v in best.items()}, open(os.path.join(RES, "best_lower_bounds.json"), "w"), indent=1)

rows = [r for r in load_jsonl(os.path.join(RES, "eval_confirm.jsonl")) if r["set"] == "fresh"]
name = {"laplace": "P1", "poisson": "P2", "pinn": "PINN", "ritz": "Deep Ritz"}
with open(os.path.join(RES, "table_eta_by_d.tex"), "w") as f:
    f.write("% generated by scripts/s8_tables.py from results/eval_confirm.jsonl (fresh set, main networks, seeds 0-2)\n")
    for prob in ("laplace", "poisson"):
        for meth in ("pinn", "ritz"):
            for d in [2, 3, 5, 10, 20]:
                s = [r for r in rows if r["family"] == "main" and r["problem"] == prob and r["method"] == meth and r["d"] == d]
                m = lambda k: sum(r[k] for r in s) / len(s)
                f.write(f"{name[prob]} & {name[meth]} & {d} & {m('rel_l2'):.3e} & {m('B_int'):.2e} & {m('B_bd'):.2e} & "
                        f"{m('eta'):.2f} ({min(r['eta'] for r in s):.2f}--{max(r['eta'] for r in s):.2f}) & "
                        f"{m('share_bd'):.3f} ({min(r['share_bd'] for r in s):.3f}--{max(r['share_bd'] for r in s):.3f}) \\\\\n")
with open(os.path.join(RES, "table_budget.tex"), "w") as f:
    f.write("% generated by scripts/s8_tables.py (fresh set, d = 10, seeds 0-2: mean (min--max))\n")
    groups = [("P1", "PINN, 4000 it.", lambda r: r["family"] == "main" and r["problem"] == "laplace" and r["method"] == "pinn" and r["d"] == 10),
              ("P1", "PINN, 16 000 it.", lambda r: r["family"] == "long" and r["problem"] == "laplace" and r["method"] == "pinn"),
              ("P1", "Deep Ritz, 4000 it.", lambda r: r["family"] == "main" and r["problem"] == "laplace" and r["method"] == "ritz" and r["d"] == 10),
              ("P1", "Deep Ritz, 16 000 it.", lambda r: r["family"] == "long" and r["problem"] == "laplace" and r["method"] == "ritz"),
              ("P1", "Deep Ritz, equal CPU (10 000 it.)", lambda r: r["family"] == "equaltime" and r["problem"] == "laplace"),
              ("P2", "PINN, 4000 it.", lambda r: r["family"] == "main" and r["problem"] == "poisson" and r["method"] == "pinn" and r["d"] == 10),
              ("P2", "Deep Ritz, 4000 it.", lambda r: r["family"] == "main" and r["problem"] == "poisson" and r["method"] == "ritz" and r["d"] == 10),
              ("P2", "Deep Ritz, equal CPU (9000 it.)", lambda r: r["family"] == "equaltime" and r["problem"] == "poisson")]
    for prob, lab, fn in groups:
        s = [r for r in rows if fn(r)]
        assert len(s) == 3, (lab, len(s))
        def mm(k, fmt):
            v = [r[k] for r in s]
            return f"{sum(v)/3:{fmt}} ({min(v):{fmt}}--{max(v):{fmt}})"
        f.write(f"{prob} & {lab} & {mm('rel_l2', '.2e')} & {mm('bound', '.3f')} & {mm('eta', '.2f')} & {mm('share_bd', '.2f')} \\\\\n")
print(open(os.path.join(RES, "table_theorem2.tex")).read())
print(open(os.path.join(RES, "table_eta_by_d.tex")).read())
print(open(os.path.join(RES, "table_budget.tex")).read())
